/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  background: {
    width: '100%',
    height: '100%',
  },
  container: {
    width: '100%',
    height: '100%',
    // backgroundColor: '#4cad7e',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 40,
    paddingBottom: 40,
    alignItems: 'center',
  },
  container2: {
    width: '100%',
    height: '100%',
    // backgroundColor: '#4cad7e',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 40,
    alignItems: 'center',
  },
  cardStartPage: {
    width: '80%',
    height: '30%',
    borderRadius: 10,
  },
  titleStarpage: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  cardTitle: {
    top: 80,
  },
  cardButton: {
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: 40,
  },
  buttonLoginawal: {
    borderRadius: 20,
    backgroundColor: '#fff',
    width: 200,
    height: 50,
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#4cad7e',
  },
  buttonLogin: {
    borderRadius: 20,
    backgroundColor: '#fff',
    width: 150,
    height: 50,
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#4cad7e',
  },
  buttonDaftar: {
    borderRadius: 20,
    backgroundColor: '#fff',
    width: 150,
    height: 50,
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#4cad7e',
    top: 20,
  },
  buttonRegister: {
    borderRadius: 20,
    backgroundColor: '#fff',
    width: 240,
    height: 50,
    justifyContent: 'center',
  },
  textButton: {
    color: '#4cad7e',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  // Style Login Page
  cardLoginPageTitle: {
    width: '100%',
    height: '45%',
  },
  cardLoginForm: {
    width: '100%',
    height: '55%',
  },
  cardLogin: {
    left: '-10%',
    width: '120%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderTopRightRadius: 240,
    borderTopLeftRadius: 240,
  },
  cardLoginreg: {
    top: -20,
    left: '-10%',
    width: '120%',
    height: '110%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderTopRightRadius: 180,
    borderTopLeftRadius: 180,
  },
  titleLoginpage: {
    fontSize: 36,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  titleFormLogin: {
    top: 80,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  inputLogin: {
    height: 50,
    width: 280,
    borderRadius: 10,
    backgroundColor: '#d0d0d0',
    color: 'black',
    padding: 10,
    marginBottom: 15,
  },
  inputLoginreg: {
    height: 50,
    width: 280,
    borderRadius: 10,
    backgroundColor: '#d0d0d0',
    color: 'black',
    padding: 10,
    // marginBottom: 10,
  },
  textTitle: {
    fontSize: 14,
    color: 'black',
    paddingTop: 10,
    right: 110,
  },
  textconfirm: {
    fontSize: 14,
    color: 'black',
    paddingTop: 10,
    right: 75,
  },
  // Style untuk UserPage
  container3: {
    width: '100%',
    height: '100%',
    // backgroundColor: '#4cad7e',
    // imageBackground: 'uri(../img/background.png)',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 40,
    alignItems: 'center',
  },
  cardWeather: {
    width: '80%',
    height: '10%',
    borderRadius: 10,
    top: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  weatherChild: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  textDate: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    left: 25,
  },
  textLocation: {
    color: 'white',
    fontSize: 14,
    textAlign: 'left',
  },
  textTempeture: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
    top: -10,
    right: 10,
  },
  cardUser: {
    width: '80%',
    height: '25%',
    backgroundColor: 'white',
    borderRadius: 10,
    top: 20,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  textGreetings: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    left: -60,
  },
  textInstructions: {
    color: 'black',
    fontSize: 14,
    textAlign: 'justify',
    paddingHorizontal: 15,
    left: -10,
  },
  buttonTaksasi: {
    width: 150,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4cad7e',
  },
  cardHistoryUser: {
    width: '80%',
    height: '25%',
    backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  textInfo: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    left: -82,
  },
  navbar: {
    width: '100%',
    height: '10%',
    backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  circleHome: {
    width: 100,
    height: 100,
    borderRadius: 100,
    bottom: 10,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#4cad7e',
  },
  imgnavbar: {
    width: 30,
    height: 30,
  },

  // Style Form Taksasi
  container4: {
    width: '100%',
    height: '100%',
    backgroundColor: '#4cad7e',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 20,
  },
  cardTopNav: {
    width: '100%',
    height: '5%',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
  },
  textTopNav: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'left',
    left: 10,
  },
  buttonTopNav: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardHandleForm: {
    width: '100%',
    height: '95%',
    backgroundColor: 'white',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    marginTop: 10,
  },
  cardForm: {
    width: '90%',
    height: '90%',
    backgroundColor: '#d5d5d5',
    borderRadius: 40,
    top: 40,
    alignSelf: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  cardList: {
    width: 340,
    height: 160,
    backgroundColor: '#4cad7e',
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  buttonAdd: {
    width: 180,
    height: 50,
    marginTop: 30,
    marginBottom: 20,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#4cad7e',
    borderRadius: 10,
    alignContent: 'center',
  },
  textButtonAdd: {
    color: '#4cad7e',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    top: 10,
  },
  buttonFinish: {
    width: 100,
    height: 50,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#4cad7e',
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    borderWidth: 2,
    borderColor: 'white',
  },
  buttonFinishclosed: {
    width: 100,
    height: 50,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#d5d5d5',
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    borderWidth: 2,
    borderColor: 'white',
  },
  textButtonFinish: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },

  // Style Admin Page
  textInstructionsAdmin: {
    color: 'black',
    fontSize: 14,
    textAlign: 'justify',
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  textInfoAdmin: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    left: -82,
  },
  styleTable: {
    width: '90%',
    // left: 15,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 10,
    // alignItems: 'center',
  },
  styleTable2: {
    width: '90%',
    left: 15,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 10,
    // alignItems: 'center',
  },
  texttab: {
    color: 'black',
    fontSize: 12,
    paddingHorizontal: 8,
    // textAlign: 'left',
    alignSelf: 'center',
    flex: 1,
    // justifyContent: 'center',
  },
  cardListUser: {
    width: '80%',
    height: '35%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  textTabAdmin: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    left: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },

  // Style Hasil Page
  scrollview: {
    margin: 20,
  },
  cardGrafik: {
    width: '90%',
    height: '80%',
    backgroundColor: '#4cad7e',
    borderRadius: 10,
    top: 10,
    flexDirection: 'column',
    alignSelf: 'center',
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardGrafikTitle: {
    width: '90%',
    height: '10%',
    backgroundColor: '#4cad7e',
    borderRadius: 10,
    top: 30,
    flexDirection: 'column',
    alignSelf: 'center',
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleresult: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  styleDatePicker: {
    top: 5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: 300,
  },

  //activityindicator
  activityIndicator: {
    alignItems: 'center',
    height: 80,
  },

  // error text
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
  },

  // style list taksasi
  cardListHandleTaksasi: {
    height: '100%',
    flexDirection: 'row',
  },
  styleBlok: {
    width: '20%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textStyleblok: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  styleDetailBlok: {
    width: '50%',
    justifyContent: 'space-around',
    flexDirection: 'column',
  },
  styleDetailBlok2: {
    width: '15%',
    justifyContent: 'space-around',
    flexDirection: 'column',
  },
  texthandleinfo: {
    color: 'white',
    fontSize: 14,
    // fontWeight: 'bold',
    textAlign: 'left',
  },
  textDetailBlok: {
    color: 'white',
    fontSize: 14,
    // fontWeight: 'bold',
    textAlign: 'right',
    left: -20,
  },
  textSatuan: {
    color: 'white',
    fontSize: 14,
    // fontWeight: 'bold',
    textAlign: 'left',
    left: -5,
  },
  texttanpadata: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
    alignSelf: 'center',
    top: 65,
  },

  //Style Modal
  modal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    width: '90%',
    height: '70%',
    backgroundColor: '#4cad7e',
    borderRadius: 20,
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalButton: {
    width: '100%',
    height: '15%',
    // backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  buttonModal: {
    backgroundColor: 'grey',
    borderWidth: 2,
    borderColor: 'white',
    width: 120,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textTitleModal: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingBottom: 10,
  },
  textModal: {
    color: 'white',
    fontSize: 14,
    textAlign: 'left',
    marginBottom: 5,
    marginTop: 5,
  },

  //tabel hasil taksasi
  tableTaksasi: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  titletext1: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 5,
    marginLeft: 10,
  },
  Table: {
    flexDirection: 'column',
  },
  textTable1: {
    color: 'white',
    fontSize: 14,
    textAlign: 'left',
  },
  textTable2: {
    color: 'white',
    fontSize: 14,
    textAlign: 'right',
  },
  cardResult: {
    weight: '100%',
    backgroundColor: '#4cad7e',
    borderColor: 'white',
    borderWidth: 1,
    margin: 10,
    borderRadius: 20,
    paddingTop: 10,
  },

  //modal drawer
  modalDrawer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 550,
    marginLeft: 230,
    marginBottom: 85,
    borderBottomStartRadius: 20,
    borderTopStartRadius: 20,
    flexDirection: 'column',
  },
});


export default styles;
